### ISSUE TITLE
steam

### ISSUE THREAD

**Issue by drakosoldier298** [MarioMasta64/EverythingPortable#11]
so i downloaded steam through this with no issues but everytime i try downloading and running a game through steam, steam asks for admin privledges

**Comment by MarioMasta64** [comment]
some games require admin privileges to install dependencies such as directx vcredist and others, if you can let me know what its installing i can see if i can get around it. for now https://github.com/MarioMasta64/DLLDownloaderPortable may help (swap the 32 and 64 folders in \dll\ ill fix that in a bit once i recover my usb) you out

**Comment by drakosoldier298** [comment]
what i am currently trying to install is stardew valley.

**Comment by MarioMasta64** [comment]
i mean what it is trying to install not the game. (exa: directx vcredist etc...)

**Comment by drakosoldier298** [comment]
ah...
Well Ill fully explain what happens. I load up steam through the program and when I install a game it fully creates the game folder and all files, that I know of, are placed in correctly but when I try to run it, steam asks for admin privileges to do the "first run setup".
I am not completely sure what it was trying to install.

**Comment by MarioMasta64** [comment]
yes but when it pops up what does it say its trying to install?
anyways the answer is these:
- https://www.microsoft.com/en-us/download/confirmation.aspx?id=20914
- http://www.microsoft.com/download/en/details.aspx?id=26999
this will have to be added to the dll downloader which atm i need to fix up.

**Comment by drakosoldier298** [comment]
i look at the thing it says its "will you let this make changes to your computer" and the last thing in the directory it shows is runasadmin.vdf
[2018-08-26 21:34:32] [AppID 413150] Failed to start SteamService with "/installscript "C:\Users\21jamlcrist\Desktop\EverythingPortable-master (1)\EverythingPortable-master\bin\steam\steamapps\common\Stardew Valley\runasadmin.vdf" 413150" (GLE 1223)
is the full error message

**Comment by MarioMasta64** [comment]
well first youll need the dll files from above, if that doesnt work then you just cant play it as the game wants admin really badly, but adding the dll files should work fine

**Comment by MarioMasta64** [comment]
choose this option (steam):
![image](https://user-images.githubusercontent.com/20806802/44756595-985a7600-aae8-11e8-9e83-4ba0a5527c1d.png)
then this one (dll downloader):
![image](https://user-images.githubusercontent.com/20806802/44756606-a27c7480-aae8-11e8-9d0f-25515302be99.png)
and it should be fixed less i missed something?
(i just added xna dll files)
reopen the issue if it isnt i guess

**Comment by logan7eleven** [comment]
hi, still having this same issue with directx runtime. redownloaded steam and all dlls but a few games are still wanting to install directx w admin rights on initial start

**Comment by logan7eleven** [comment]
> hi, still having this same issue with directx runtime. redownloaded steam and all dlls but a few games are still wanting to install directx w admin rights on initial start

actually got it to work. did a few things but I think switching the names of the 32 and 64 dll folders did it.
